### ISSUE TITLE
OpenVINIO support

### ISSUE THREAD

**Issue by oldma3095** [yalue/onnxruntime_go#34] opened 2024-01-24 08:15 UTC
Hi,
Is there plan to support OpenVINO?

Thanks

**Comment by yalue** [comment] 2024-01-24 14:33
Hi!  As with all of the other execution providers, I never really "plan" to support them, but I will generally look into adding support if someone requests it.  Often the issue is my own lack of hardware or testing systems, so I rely on an interested requester to test new code for me--and in this case I don't have a recent Intel CPU or GPU for testing.

That being said, enabling OpenVINO looks like it will be possible.  It would likely take the form of `func (o *SessionOptions) AppendExecutionProviderOpenVINO(map[string]string options) error`, where the map contains the string options specified by the `C/C++ API 2.0" string options described in https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#cc-api-20.  Internally, it would need to call `SessionOptionsAppendExecutionProvider_OpenVINO_V2`.  (These are largely notes to myself.)

I'll look into it when I have free time.  I can probably get to it this weekend, but as always this just remains a personal side project to me so I can't make any guarantees.  If I have it set up, would you be willing to run the unit tests for me?

**Comment by oldma3095** [comment] 2024-01-25 03:10
Of course, I have successfully tested using cuda and trt.
If it can support openvino, I will test it and get back to you with the results.
Thank you very much.

**Comment by yalue** [comment] 2024-01-29 14:12
Just a quick update here: the `SessionOptionsAppendExecutionProvier_OpenVINO_V2` is already in the bleeding edge `onnxruntime` API, but it actually is not yet in version 1.16.3.  The commit adding the function is [here](https://github.com/microsoft/onnxruntime/commit/c340bf08f602ba269245c46244435810ee3a52c3), and indicates that the functionality should be available in onnxruntime version 1.17.

While I could wrap the version of `SessionOptionsAppendExecutionProvider_OpenVINO` that's already in onnxruntime version 1.16, I would prefer not to, since it would require wrapping yet another settings struct and will quite possibly be deprecated in favor of the string-configured version as soon as version 1.17 is released.

Onnxruntime's [upcoming releases roadmap](https://github.com/microsoft/onnxruntime/wiki/Upcoming-Release-Roadmap) seems to have expected 1.17 to have released in December, though obviously that hasn't happened yet.  However, I expect it will be released within a month or so.  I'll plan to add OpenVINO support to `onnxruntime_go` after I update it to use 1.17, and until then I'll keep this issue open as a reminder.  Sorry for the delay!

**Comment by oldma3095** [comment] 2024-01-31 02:48
Fine.
I can use CUDA or TRT before 1.17
Thank you for your reply.

**Comment by oldma3095** [comment] 2024-02-05 09:40
Hi,
onnxruntime 1.17 has released.
![image](https://github.com/yalue/onnxruntime_go/assets/43288861/b47b7557-b547-4d49-9a1f-c6178a81b141)

**Comment by yalue** [comment] 2024-02-29 01:15
Sorry that this was quite a delay!  However, I've now added the API as planned.  If you're still interested in testing it out, would you mind checking out the `add_openvino_support` branch, running `go test -v -bench=.`, and making sure that the OpenVINO test and benchmark pass rather than fail or get skipped?

Looks like you'll need to follow the instructions here: https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html i.e., running OpenVINO's `setupvars.bat` on Windows or `source setupvars.sh` on Linux, though I suppose you know that already.  (I wanted to include it here in case anyone else sees this issue and wants to try it out.)

If I don't hear back from you I'll probably just merge the PR in a week or two, since it at least isn't breaking any existing tests, and it doesn't seem like there's much I could have messed up on the Go side.

**Comment by oldma3095** [comment] 2024-03-04 08:57
I used the yolov5 and yolov8 models to test object detection, which proved that openvino_cpu and openvino_cpu are effective.

But a problem was discovered. 
After openvino_cpu sets the num_of_threads and num_streams parameters, the maximum CPU usage will be fixed at 100%. 
After openvino_gpu sets the num_of_threads and num_streams parameters, the maximum CPU usage will be fixed at 200%.

I'm not sure if this is an issue with onnxruntime.

![image](https://github.com/yalue/onnxruntime_go/assets/43288861/6938387f-8936-4bc3-a3b0-a282943c802e)

**Comment by yalue** [comment] 2024-03-04 13:38
Hm, interesting.  My main concern is whether the API correctly enabled the execution provider, since that's all I have control over in the wrapper.  All the Go code does is invoke the onnxruntime API; nothing that will either consume or limit CPU utilization.  So, I'll probably merge the PR and close this issue.  However, if you do discover that there's a separate API you need access to in order to address the issue you're seeing, feel free to let me know.

Thank you again for testing it, and for your patience!

**Closed by yalue** 2024-03-04 13:38 UTC
